apiVersion: v1
kind: Service
metadata:
  name: genai
spec:
  selector:
    app: genai
  ports:
    - protocol: TCP
      port: 3001  # External port
      targetPort: 3001  # Port your container is listening on
  type: NodePort  # Change to "NodePort" if not using a cloud provider
